name: CD to Staging

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist/

    - name: Deploy to Staging
      env:
        STAGING_SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
        STAGING_HOST: ${{ secrets.STAGING_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$STAGING_SSH_KEY" > ~/.ssh/staging_key
        chmod 600 ~/.ssh/staging_key
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/staging_key ubuntu@$STAGING_HOST 'cd /path/to/staging/app && git pull origin main && npm ci && npm run build && npm start'